import dynamic from 'next/dynamic';

import Head from 'next/head'

const Header = dynamic(() => import("./Navigation"));
const Footer = dynamic(() => import("./Footer"));

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

function Layout({ children, title = 'Book Best Place for your Holiday' }) {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by V.Ganchev" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <ToastContainer position='bottom-right' />
            {children}
            <Footer />
        </div>
    )
}
export default Layout;