import Head from 'next/head'
import Navigation from './Navigation'
import Footer from './Footer'

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function Layout({ children, title = 'Book Best Place for your Holiday' }) {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by V.Ganchev" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <ToastContainer position='bottom-right' />
            {children}
            <Footer />
        </div>
    )
}
