import Head from 'next/head'
//import { Inter } from '@next/font/google'
//const inter = Inter({ subsets: ['latin'] })

import Navigation from './Navigation'
import Footer from './Footer'


export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>Real-Estate</title>
                <meta name="description" content="Generated by Ganchev" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css"></link>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <div>
                {children}
            </div>
            <Footer />
        </div>
    )
}
