import Head from 'next/head'
//import { Inter } from '@next/font/google'
//const inter = Inter({ subsets: ['latin'] })

import Navigation from '../components/Navigation'
import Footer from '../components/Footer'


export default function Layout({ children }) {
    return (
        <div >
            <Head>
                <title>Real-Estate</title>
                <meta name="description" content="Generated by Ganchev" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <div className='container'>
                {children}
            </div>
            <Footer />
        </div>
    )
}
