export const ALL_PLACES_SUCCESS = 'ALL_PLACES_SUCCESS'
export const ALL_PLACES_FAIL = 'ALL_PLACES_FAIL'

export const PLACE_DETAILS_SUCCESS = 'PLACE_DETAILS_SUCCESS'
export const PLACE_DETAILS_FAIL = 'PLACE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'